# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2014.4
# Copyright (C) 2014 Xilinx Inc. All rights reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado_HLS/2014.4/../../Vivado/2014.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7k410tffg900-2 ../xilinx_com_hls_sosf_detector_top_1_0.zip
