// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "filter_top_dummy_proc_fe.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic filter_top_dummy_proc_fe::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filter_top_dummy_proc_fe::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> filter_top_dummy_proc_fe::ap_ST_st1_fsm_0 = "1";
const sc_lv<6> filter_top_dummy_proc_fe::ap_ST_st2_fsm_1 = "10";
const sc_lv<6> filter_top_dummy_proc_fe::ap_ST_st3_fsm_2 = "100";
const sc_lv<6> filter_top_dummy_proc_fe::ap_ST_st4_fsm_3 = "1000";
const sc_lv<6> filter_top_dummy_proc_fe::ap_ST_st5_fsm_4 = "10000";
const sc_lv<6> filter_top_dummy_proc_fe::ap_ST_st6_fsm_5 = "100000";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> filter_top_dummy_proc_fe::ap_const_lv1_1 = "1";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_1 = "1";
const sc_lv<1> filter_top_dummy_proc_fe::ap_const_lv1_0 = "0";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_2 = "10";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_3 = "11";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_4 = "100";
const sc_lv<12> filter_top_dummy_proc_fe::ap_const_lv12_0 = "000000000000";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_5 = "101";
const sc_lv<16> filter_top_dummy_proc_fe::ap_const_lv16_0 = "0000000000000000";
const sc_lv<13> filter_top_dummy_proc_fe::ap_const_lv13_C3F = "110000111111";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_C = "1100";
const sc_lv<13> filter_top_dummy_proc_fe::ap_const_lv13_2 = "10";
const sc_lv<12> filter_top_dummy_proc_fe::ap_const_lv12_800 = "100000000000";
const sc_lv<12> filter_top_dummy_proc_fe::ap_const_lv12_1 = "1";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_9 = "1001";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_B = "1011";
const sc_lv<3> filter_top_dummy_proc_fe::ap_const_lv3_0 = "000";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_20 = "100000";
const sc_lv<32> filter_top_dummy_proc_fe::ap_const_lv32_3F = "111111";
const sc_lv<12> filter_top_dummy_proc_fe::ap_const_lv12_5FF = "10111111111";

filter_top_dummy_proc_fe::filter_top_dummy_proc_fe(sc_module_name name) : sc_module(name), mVcdFile(0) {
    detector_tail_M_real_V_U = new filter_top_dummy_proc_fe_detector_tail_M_real_V("detector_tail_M_real_V_U");
    detector_tail_M_real_V_U->clk(ap_clk);
    detector_tail_M_real_V_U->reset(ap_rst);
    detector_tail_M_real_V_U->address0(detector_tail_M_real_V_address0);
    detector_tail_M_real_V_U->ce0(detector_tail_M_real_V_ce0);
    detector_tail_M_real_V_U->we0(detector_tail_M_real_V_we0);
    detector_tail_M_real_V_U->d0(detector_tail_M_real_V_d0);
    detector_tail_M_real_V_U->q0(detector_tail_M_real_V_q0);
    detector_tail_M_imag_V_U = new filter_top_dummy_proc_fe_detector_tail_M_real_V("detector_tail_M_imag_V_U");
    detector_tail_M_imag_V_U->clk(ap_clk);
    detector_tail_M_imag_V_U->reset(ap_rst);
    detector_tail_M_imag_V_U->address0(detector_tail_M_imag_V_address0);
    detector_tail_M_imag_V_U->ce0(detector_tail_M_imag_V_ce0);
    detector_tail_M_imag_V_U->we0(detector_tail_M_imag_V_we0);
    detector_tail_M_imag_V_U->d0(detector_tail_M_imag_V_d0);
    detector_tail_M_imag_V_U->q0(detector_tail_M_imag_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_210_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_210_p2 );

    SC_METHOD(thread_ap_sig_bdd_107);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_117);
    sensitive << ( in_r_ap_vld );
    sensitive << ( output_xn1_full_n );
    sensitive << ( output_xn2_full_n );
    sensitive << ( icmp_fu_237_p2 );

    SC_METHOD(thread_ap_sig_bdd_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_145);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( config_fwd_data_V_full_n );
    sensitive << ( config_inv_data_V_full_n );

    SC_METHOD(thread_ap_sig_bdd_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_158);
    sensitive << ( output_xn1_full_n );
    sensitive << ( icmp_reg_306 );

    SC_METHOD(thread_ap_sig_bdd_167);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_ap_sig_bdd_25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_82);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_98);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_25 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_82 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_98 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_107 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_132 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_153 );

    SC_METHOD(thread_config_fwd_data_V_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_config_fwd_data_V_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_config_inv_data_V_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_config_inv_data_V_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_detector_tail_M_imag_V_address0);
    sensitive << ( tmp_reg_290 );
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_269_p1 );
    sensitive << ( ap_sig_bdd_167 );

    SC_METHOD(thread_detector_tail_M_imag_V_ce0);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_detector_tail_M_imag_V_d0);
    sensitive << ( in_r );
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_detector_tail_M_imag_V_we0);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_detector_tail_M_real_V_address0);
    sensitive << ( tmp_reg_290 );
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_269_p1 );
    sensitive << ( ap_sig_bdd_167 );

    SC_METHOD(thread_detector_tail_M_real_V_ce0);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_detector_tail_M_real_V_d0);
    sensitive << ( in_r );
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_detector_tail_M_real_V_we0);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( tmp_4_fu_259_p2 );

    SC_METHOD(thread_exitcond_fu_210_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_171 );

    SC_METHOD(thread_i_1_fu_216_p2);
    sensitive << ( i_reg_171 );

    SC_METHOD(thread_icmp_fu_237_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( tmp_1_fu_227_p4 );

    SC_METHOD(thread_in_r_ap_ack);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );

    SC_METHOD(thread_input_xn2_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_222_p1 );

    SC_METHOD(thread_input_xn2_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_output_xn1_M_imag_V_addr_fu_275_p3);
    sensitive << ( detector_tail_M_real_V_load_reg_323 );
    sensitive << ( detector_tail_M_imag_V_load_reg_328 );

    SC_METHOD(thread_output_xn1_din);
    sensitive << ( in_r );
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( icmp_reg_306 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_bdd_158 );
    sensitive << ( output_xn1_M_imag_V_addr_fu_275_p3 );

    SC_METHOD(thread_output_xn1_write);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( icmp_reg_306 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_bdd_158 );

    SC_METHOD(thread_output_xn2_din);
    sensitive << ( input_xn2_load_reg_301 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );

    SC_METHOD(thread_output_xn2_write);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );

    SC_METHOD(thread_tmp_1_fu_227_p4);
    sensitive << ( i_reg_171 );

    SC_METHOD(thread_tmp_3_fu_265_p1);
    sensitive << ( i_reg_171 );

    SC_METHOD(thread_tmp_4_fu_259_p2);
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( i_reg_171 );

    SC_METHOD(thread_tmp_6_fu_269_p1);
    sensitive << ( tmp_3_fu_265_p1 );

    SC_METHOD(thread_tmp_fu_222_p1);
    sensitive << ( i_reg_171 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_210_p2 );
    sensitive << ( icmp_fu_237_p2 );
    sensitive << ( ap_sig_bdd_117 );
    sensitive << ( ap_sig_bdd_145 );
    sensitive << ( ap_sig_bdd_158 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filter_top_dummy_proc_fe_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, config_fwd_data_V_din, "(port)config_fwd_data_V_din");
    sc_trace(mVcdFile, config_fwd_data_V_full_n, "(port)config_fwd_data_V_full_n");
    sc_trace(mVcdFile, config_fwd_data_V_write, "(port)config_fwd_data_V_write");
    sc_trace(mVcdFile, config_inv_data_V_din, "(port)config_inv_data_V_din");
    sc_trace(mVcdFile, config_inv_data_V_full_n, "(port)config_inv_data_V_full_n");
    sc_trace(mVcdFile, config_inv_data_V_write, "(port)config_inv_data_V_write");
    sc_trace(mVcdFile, in_r, "(port)in_r");
    sc_trace(mVcdFile, in_r_ap_vld, "(port)in_r_ap_vld");
    sc_trace(mVcdFile, in_r_ap_ack, "(port)in_r_ap_ack");
    sc_trace(mVcdFile, input_xn2_address0, "(port)input_xn2_address0");
    sc_trace(mVcdFile, input_xn2_ce0, "(port)input_xn2_ce0");
    sc_trace(mVcdFile, input_xn2_q0, "(port)input_xn2_q0");
    sc_trace(mVcdFile, output_xn1_din, "(port)output_xn1_din");
    sc_trace(mVcdFile, output_xn1_full_n, "(port)output_xn1_full_n");
    sc_trace(mVcdFile, output_xn1_write, "(port)output_xn1_write");
    sc_trace(mVcdFile, output_xn2_din, "(port)output_xn2_din");
    sc_trace(mVcdFile, output_xn2_full_n, "(port)output_xn2_full_n");
    sc_trace(mVcdFile, output_xn2_write, "(port)output_xn2_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_25, "ap_sig_bdd_25");
    sc_trace(mVcdFile, detector_tail_M_real_V_address0, "detector_tail_M_real_V_address0");
    sc_trace(mVcdFile, detector_tail_M_real_V_ce0, "detector_tail_M_real_V_ce0");
    sc_trace(mVcdFile, detector_tail_M_real_V_we0, "detector_tail_M_real_V_we0");
    sc_trace(mVcdFile, detector_tail_M_real_V_d0, "detector_tail_M_real_V_d0");
    sc_trace(mVcdFile, detector_tail_M_real_V_q0, "detector_tail_M_real_V_q0");
    sc_trace(mVcdFile, detector_tail_M_imag_V_address0, "detector_tail_M_imag_V_address0");
    sc_trace(mVcdFile, detector_tail_M_imag_V_ce0, "detector_tail_M_imag_V_ce0");
    sc_trace(mVcdFile, detector_tail_M_imag_V_we0, "detector_tail_M_imag_V_we0");
    sc_trace(mVcdFile, detector_tail_M_imag_V_d0, "detector_tail_M_imag_V_d0");
    sc_trace(mVcdFile, detector_tail_M_imag_V_q0, "detector_tail_M_imag_V_q0");
    sc_trace(mVcdFile, i_1_fu_216_p2, "i_1_fu_216_p2");
    sc_trace(mVcdFile, i_1_reg_285, "i_1_reg_285");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_82, "ap_sig_bdd_82");
    sc_trace(mVcdFile, tmp_fu_222_p1, "tmp_fu_222_p1");
    sc_trace(mVcdFile, tmp_reg_290, "tmp_reg_290");
    sc_trace(mVcdFile, exitcond_fu_210_p2, "exitcond_fu_210_p2");
    sc_trace(mVcdFile, input_xn2_load_reg_301, "input_xn2_load_reg_301");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_98, "ap_sig_bdd_98");
    sc_trace(mVcdFile, icmp_fu_237_p2, "icmp_fu_237_p2");
    sc_trace(mVcdFile, icmp_reg_306, "icmp_reg_306");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_107, "ap_sig_bdd_107");
    sc_trace(mVcdFile, ap_sig_bdd_117, "ap_sig_bdd_117");
    sc_trace(mVcdFile, detector_tail_M_real_V_load_reg_323, "detector_tail_M_real_V_load_reg_323");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_132, "ap_sig_bdd_132");
    sc_trace(mVcdFile, detector_tail_M_imag_V_load_reg_328, "detector_tail_M_imag_V_load_reg_328");
    sc_trace(mVcdFile, i_reg_171, "i_reg_171");
    sc_trace(mVcdFile, ap_sig_bdd_145, "ap_sig_bdd_145");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_153, "ap_sig_bdd_153");
    sc_trace(mVcdFile, ap_sig_bdd_158, "ap_sig_bdd_158");
    sc_trace(mVcdFile, tmp_6_fu_269_p1, "tmp_6_fu_269_p1");
    sc_trace(mVcdFile, tmp_4_fu_259_p2, "tmp_4_fu_259_p2");
    sc_trace(mVcdFile, output_xn1_M_imag_V_addr_fu_275_p3, "output_xn1_M_imag_V_addr_fu_275_p3");
    sc_trace(mVcdFile, tmp_1_fu_227_p4, "tmp_1_fu_227_p4");
    sc_trace(mVcdFile, tmp_3_fu_265_p1, "tmp_3_fu_265_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_167, "ap_sig_bdd_167");
#endif

    }
}

filter_top_dummy_proc_fe::~filter_top_dummy_proc_fe() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete detector_tail_M_real_V_U;
    delete detector_tail_M_imag_V_U;
}

void filter_top_dummy_proc_fe::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond_fu_210_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !ap_sig_bdd_158.read())) {
        i_reg_171 = i_1_reg_285.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_145.read())) {
        i_reg_171 = ap_const_lv12_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        detector_tail_M_imag_V_load_reg_328 = detector_tail_M_imag_V_q0.read();
        detector_tail_M_real_V_load_reg_323 = detector_tail_M_real_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_1_reg_285 = i_1_fu_216_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && !ap_sig_bdd_117.read())) {
        icmp_reg_306 = icmp_fu_237_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        input_xn2_load_reg_301 = input_xn2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_fu_210_p2.read(), ap_const_lv1_0))) {
        tmp_reg_290 = tmp_fu_222_p1.read();
    }
}

void filter_top_dummy_proc_fe::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_210_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond_fu_210_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_107() {
    ap_sig_bdd_107 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_117() {
    ap_sig_bdd_117 = (esl_seteq<1,1,1>(output_xn2_full_n.read(), ap_const_logic_0) || (esl_seteq<1,1,1>(in_r_ap_vld.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
  esl_seteq<1,1,1>(output_xn1_full_n.read(), ap_const_logic_0)));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_132() {
    ap_sig_bdd_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_145() {
    ap_sig_bdd_145 = (esl_seteq<1,1,1>(config_fwd_data_V_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(config_inv_data_V_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_153() {
    ap_sig_bdd_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_158() {
    ap_sig_bdd_158 = (esl_seteq<1,1,1>(output_xn1_full_n.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, icmp_reg_306.read()));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_167() {
    ap_sig_bdd_167 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_259_p2.read()));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_25() {
    ap_sig_bdd_25 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_82() {
    ap_sig_bdd_82 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void filter_top_dummy_proc_fe::thread_ap_sig_bdd_98() {
    ap_sig_bdd_98 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void filter_top_dummy_proc_fe::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_25.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_82.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_98.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_107.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_132.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_153.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_config_fwd_data_V_din() {
    config_fwd_data_V_din = esl_partset<16,16,13,32,32>(ap_const_lv16_0, ap_const_lv13_C3F, ap_const_lv32_0, ap_const_lv32_C);
}

void filter_top_dummy_proc_fe::thread_config_fwd_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_145.read())) {
        config_fwd_data_V_write = ap_const_logic_1;
    } else {
        config_fwd_data_V_write = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_config_inv_data_V_din() {
    config_inv_data_V_din = esl_partset<16,16,13,32,32>(ap_const_lv16_0, ap_const_lv13_2, ap_const_lv32_0, ap_const_lv32_C);
}

void filter_top_dummy_proc_fe::thread_config_inv_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_145.read())) {
        config_inv_data_V_write = ap_const_logic_1;
    } else {
        config_inv_data_V_write = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_imag_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        if (ap_sig_bdd_167.read()) {
            detector_tail_M_imag_V_address0 =  (sc_lv<9>) (tmp_6_fu_269_p1.read());
        } else if (!esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read())) {
            detector_tail_M_imag_V_address0 =  (sc_lv<9>) (tmp_reg_290.read());
        } else {
            detector_tail_M_imag_V_address0 = "XXXXXXXXX";
        }
    } else {
        detector_tail_M_imag_V_address0 = "XXXXXXXXX";
    }
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_imag_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !ap_sig_bdd_117.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
          !ap_sig_bdd_117.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_259_p2.read())))) {
        detector_tail_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        detector_tail_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_imag_V_d0() {
    detector_tail_M_imag_V_d0 = in_r.read().range(63, 32);
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_imag_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
          !ap_sig_bdd_117.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_259_p2.read())))) {
        detector_tail_M_imag_V_we0 = ap_const_logic_1;
    } else {
        detector_tail_M_imag_V_we0 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_real_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        if (ap_sig_bdd_167.read()) {
            detector_tail_M_real_V_address0 =  (sc_lv<9>) (tmp_6_fu_269_p1.read());
        } else if (!esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read())) {
            detector_tail_M_real_V_address0 =  (sc_lv<9>) (tmp_reg_290.read());
        } else {
            detector_tail_M_real_V_address0 = "XXXXXXXXX";
        }
    } else {
        detector_tail_M_real_V_address0 = "XXXXXXXXX";
    }
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_real_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !ap_sig_bdd_117.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
          !ap_sig_bdd_117.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_259_p2.read())))) {
        detector_tail_M_real_V_ce0 = ap_const_logic_1;
    } else {
        detector_tail_M_real_V_ce0 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_real_V_d0() {
    detector_tail_M_real_V_d0 = in_r.read().range(32-1, 0);
}

void filter_top_dummy_proc_fe::thread_detector_tail_M_real_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
          !ap_sig_bdd_117.read() && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_259_p2.read())))) {
        detector_tail_M_real_V_we0 = ap_const_logic_1;
    } else {
        detector_tail_M_real_V_we0 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_exitcond_fu_210_p2() {
    exitcond_fu_210_p2 = (!i_reg_171.read().is_01() || !ap_const_lv12_800.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_171.read() == ap_const_lv12_800);
}

void filter_top_dummy_proc_fe::thread_i_1_fu_216_p2() {
    i_1_fu_216_p2 = (!i_reg_171.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(i_reg_171.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void filter_top_dummy_proc_fe::thread_icmp_fu_237_p2() {
    icmp_fu_237_p2 = (!tmp_1_fu_227_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_227_p4.read() == ap_const_lv3_0);
}

void filter_top_dummy_proc_fe::thread_in_r_ap_ack() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
         !ap_sig_bdd_117.read())) {
        in_r_ap_ack = ap_const_logic_1;
    } else {
        in_r_ap_ack = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_input_xn2_address0() {
    input_xn2_address0 =  (sc_lv<11>) (tmp_fu_222_p1.read());
}

void filter_top_dummy_proc_fe::thread_input_xn2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        input_xn2_ce0 = ap_const_logic_1;
    } else {
        input_xn2_ce0 = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_output_xn1_M_imag_V_addr_fu_275_p3() {
    output_xn1_M_imag_V_addr_fu_275_p3 = esl_concat<32,32>(detector_tail_M_imag_V_load_reg_328.read(), detector_tail_M_real_V_load_reg_323.read());
}

void filter_top_dummy_proc_fe::thread_output_xn1_din() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, icmp_reg_306.read()) && 
         !ap_sig_bdd_158.read())) {
        output_xn1_din = output_xn1_M_imag_V_addr_fu_275_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
                !ap_sig_bdd_117.read())) {
        output_xn1_din = in_r.read();
    } else {
        output_xn1_din =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void filter_top_dummy_proc_fe::thread_output_xn1_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && 
          !ap_sig_bdd_117.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, icmp_reg_306.read()) && 
          !ap_sig_bdd_158.read()))) {
        output_xn1_write = ap_const_logic_1;
    } else {
        output_xn1_write = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_output_xn2_din() {
    output_xn2_din = input_xn2_load_reg_301.read();
}

void filter_top_dummy_proc_fe::thread_output_xn2_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !ap_sig_bdd_117.read())) {
        output_xn2_write = ap_const_logic_1;
    } else {
        output_xn2_write = ap_const_logic_0;
    }
}

void filter_top_dummy_proc_fe::thread_tmp_1_fu_227_p4() {
    tmp_1_fu_227_p4 = i_reg_171.read().range(11, 9);
}

void filter_top_dummy_proc_fe::thread_tmp_3_fu_265_p1() {
    tmp_3_fu_265_p1 = i_reg_171.read().range(9-1, 0);
}

void filter_top_dummy_proc_fe::thread_tmp_4_fu_259_p2() {
    tmp_4_fu_259_p2 = (!i_reg_171.read().is_01() || !ap_const_lv12_5FF.is_01())? sc_lv<1>(): (sc_biguint<12>(i_reg_171.read()) > sc_biguint<12>(ap_const_lv12_5FF));
}

void filter_top_dummy_proc_fe::thread_tmp_6_fu_269_p1() {
    tmp_6_fu_269_p1 = esl_zext<64,9>(tmp_3_fu_265_p1.read());
}

void filter_top_dummy_proc_fe::thread_tmp_fu_222_p1() {
    tmp_fu_222_p1 = esl_zext<64,12>(i_reg_171.read());
}

void filter_top_dummy_proc_fe::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_145.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond_fu_210_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()) && !ap_sig_bdd_117.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else if ((!ap_sig_bdd_117.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_237_p2.read()))) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            if (!ap_sig_bdd_158.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

