// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _filter_top_HH_
#define _filter_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dummy_proc_fe.h"
#include "fft_config1_s.h"
#include "fft_config2_s.h"
#include "dummy_proc_be.h"
#include "fifo_w16_d2048_A.h"
#include "fifo_w64_d1344_A.h"
#include "fifo_w64_d64_A.h"

namespace ap_rtl {

struct filter_top : public sc_module {
    // Port declarations 27
    sc_out< sc_lv<11> > coefs_address0;
    sc_out< sc_logic > coefs_ce0;
    sc_out< sc_lv<64> > coefs_d0;
    sc_in< sc_lv<64> > coefs_q0;
    sc_out< sc_logic > coefs_we0;
    sc_in< sc_lv<64> > in_r_dout;
    sc_in< sc_logic > in_r_empty_n;
    sc_out< sc_logic > in_r_read;
    sc_out< sc_lv<11> > inxn2_address0;
    sc_out< sc_logic > inxn2_ce0;
    sc_out< sc_lv<64> > inxn2_d0;
    sc_in< sc_lv<64> > inxn2_q0;
    sc_out< sc_logic > inxn2_we0;
    sc_out< sc_lv<11> > outxk1_address0;
    sc_out< sc_logic > outxk1_ce0;
    sc_out< sc_lv<64> > outxk1_d0;
    sc_in< sc_lv<64> > outxk1_q0;
    sc_out< sc_logic > outxk1_we0;
    sc_out< sc_lv<64> > out_r_din;
    sc_in< sc_logic > out_r_full_n;
    sc_out< sc_logic > out_r_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    filter_top(sc_module_name name);
    SC_HAS_PROCESS(filter_top);

    ~filter_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    dummy_proc_fe* dummy_proc_fe_U0;
    fft_config1_s* fft_config1_U0;
    fft_config2_s* fft_config2_U0;
    dummy_proc_be* dummy_proc_be_U0;
    fifo_w16_d2048_A* fft_config_fwd_data_s_U;
    fifo_w16_d2048_A* fft_config_inv_data_s_U;
    fifo_w64_d1344_A* xn_channel_U;
    fifo_w64_d64_A* xn2_channel_U;
    fifo_w64_d64_A* xk_channel_U;
    fifo_w64_d64_A* xk2_channel_U;
    sc_signal< sc_logic > dummy_proc_fe_U0_ap_start;
    sc_signal< sc_logic > dummy_proc_fe_U0_ap_done;
    sc_signal< sc_logic > dummy_proc_fe_U0_ap_continue;
    sc_signal< sc_logic > dummy_proc_fe_U0_ap_idle;
    sc_signal< sc_logic > dummy_proc_fe_U0_ap_ready;
    sc_signal< sc_lv<16> > dummy_proc_fe_U0_config_fwd_data_V_din;
    sc_signal< sc_logic > dummy_proc_fe_U0_config_fwd_data_V_write;
    sc_signal< sc_lv<16> > dummy_proc_fe_U0_config_inv_data_V_din;
    sc_signal< sc_logic > dummy_proc_fe_U0_config_inv_data_V_write;
    sc_signal< sc_logic > dummy_proc_fe_U0_in_r_read;
    sc_signal< sc_lv<11> > dummy_proc_fe_U0_input_xn2_address0;
    sc_signal< sc_logic > dummy_proc_fe_U0_input_xn2_ce0;
    sc_signal< sc_lv<64> > dummy_proc_fe_U0_output_xn1_din;
    sc_signal< sc_logic > dummy_proc_fe_U0_output_xn1_write;
    sc_signal< sc_lv<64> > dummy_proc_fe_U0_output_xn2_din;
    sc_signal< sc_logic > dummy_proc_fe_U0_output_xn2_write;
    sc_signal< sc_logic > fft_config1_U0_ap_start;
    sc_signal< sc_logic > fft_config1_U0_ap_done;
    sc_signal< sc_logic > fft_config1_U0_ap_idle;
    sc_signal< sc_logic > fft_config1_U0_ap_ready;
    sc_signal< sc_logic > fft_config1_U0_xn_read;
    sc_signal< sc_lv<64> > fft_config1_U0_xk_din;
    sc_signal< sc_logic > fft_config1_U0_xk_write;
    sc_signal< sc_lv<8> > fft_config1_U0_status_data_V_din;
    sc_signal< sc_logic > fft_config1_U0_status_data_V_write;
    sc_signal< sc_logic > fft_config1_U0_config_ch_data_V_read;
    sc_signal< sc_logic > fft_config2_U0_ap_start;
    sc_signal< sc_logic > fft_config2_U0_ap_done;
    sc_signal< sc_logic > fft_config2_U0_ap_idle;
    sc_signal< sc_logic > fft_config2_U0_ap_ready;
    sc_signal< sc_logic > fft_config2_U0_xn_read;
    sc_signal< sc_lv<64> > fft_config2_U0_xk_din;
    sc_signal< sc_logic > fft_config2_U0_xk_write;
    sc_signal< sc_lv<8> > fft_config2_U0_status_data_V_din;
    sc_signal< sc_logic > fft_config2_U0_status_data_V_write;
    sc_signal< sc_logic > fft_config2_U0_config_ch_data_V_read;
    sc_signal< sc_logic > dummy_proc_be_U0_ap_start;
    sc_signal< sc_logic > dummy_proc_be_U0_ap_done;
    sc_signal< sc_logic > dummy_proc_be_U0_ap_continue;
    sc_signal< sc_logic > dummy_proc_be_U0_ap_idle;
    sc_signal< sc_logic > dummy_proc_be_U0_ap_ready;
    sc_signal< sc_lv<11> > dummy_proc_be_U0_coefs_address0;
    sc_signal< sc_logic > dummy_proc_be_U0_coefs_ce0;
    sc_signal< sc_logic > dummy_proc_be_U0_input_xk1_read;
    sc_signal< sc_logic > dummy_proc_be_U0_input_xk2_read;
    sc_signal< sc_lv<11> > dummy_proc_be_U0_output_xk1_address0;
    sc_signal< sc_logic > dummy_proc_be_U0_output_xk1_ce0;
    sc_signal< sc_logic > dummy_proc_be_U0_output_xk1_we0;
    sc_signal< sc_lv<64> > dummy_proc_be_U0_output_xk1_d0;
    sc_signal< sc_lv<64> > dummy_proc_be_U0_out_r_din;
    sc_signal< sc_logic > dummy_proc_be_U0_out_r_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > fft_config_fwd_data_s_full_n;
    sc_signal< sc_lv<16> > fft_config_fwd_data_s_dout;
    sc_signal< sc_logic > fft_config_fwd_data_s_empty_n;
    sc_signal< sc_logic > fft_config_inv_data_s_full_n;
    sc_signal< sc_lv<16> > fft_config_inv_data_s_dout;
    sc_signal< sc_logic > fft_config_inv_data_s_empty_n;
    sc_signal< sc_logic > xn_channel_full_n;
    sc_signal< sc_lv<64> > xn_channel_dout;
    sc_signal< sc_logic > xn_channel_empty_n;
    sc_signal< sc_logic > xn2_channel_full_n;
    sc_signal< sc_lv<64> > xn2_channel_dout;
    sc_signal< sc_logic > xn2_channel_empty_n;
    sc_signal< sc_logic > xk_channel_full_n;
    sc_signal< sc_lv<64> > xk_channel_dout;
    sc_signal< sc_logic > xk_channel_empty_n;
    sc_signal< sc_logic > xk2_channel_full_n;
    sc_signal< sc_lv<64> > xk2_channel_dout;
    sc_signal< sc_logic > xk2_channel_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_dummy_proc_be_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_dummy_proc_be_U0_ap_ready;
    sc_signal< sc_lv<2> > dummy_proc_be_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_dummy_proc_fe_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_dummy_proc_fe_U0_ap_ready;
    sc_signal< sc_lv<2> > dummy_proc_fe_U0_ap_ready_count;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_dummy_proc_be_U0_ap_ready();
    void thread_ap_sync_dummy_proc_fe_U0_ap_ready();
    void thread_ap_sync_ready();
    void thread_coefs_address0();
    void thread_coefs_ce0();
    void thread_coefs_d0();
    void thread_coefs_we0();
    void thread_dummy_proc_be_U0_ap_continue();
    void thread_dummy_proc_be_U0_ap_start();
    void thread_dummy_proc_fe_U0_ap_continue();
    void thread_dummy_proc_fe_U0_ap_start();
    void thread_in_r_read();
    void thread_inxn2_address0();
    void thread_inxn2_ce0();
    void thread_inxn2_d0();
    void thread_inxn2_we0();
    void thread_out_r_din();
    void thread_out_r_write();
    void thread_outxk1_address0();
    void thread_outxk1_ce0();
    void thread_outxk1_d0();
    void thread_outxk1_we0();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
