// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filter_top,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k410tffg900-2,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.887500,HLS_SYN_LAT=18433,HLS_SYN_TPT=18434,HLS_SYN_MEM=58,HLS_SYN_DSP=96,HLS_SYN_FF=38126,HLS_SYN_LUT=30337}" *)

module filter_top (
        coefs_address0,
        coefs_ce0,
        coefs_d0,
        coefs_q0,
        coefs_we0,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        inxn2_address0,
        inxn2_ce0,
        inxn2_d0,
        inxn2_q0,
        inxn2_we0,
        outxk1_address0,
        outxk1_ce0,
        outxk1_d0,
        outxk1_q0,
        outxk1_we0,
        out_r_din,
        out_r_full_n,
        out_r_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);


output  [10:0] coefs_address0;
output   coefs_ce0;
output  [63:0] coefs_d0;
input  [63:0] coefs_q0;
output   coefs_we0;
input  [63:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [10:0] inxn2_address0;
output   inxn2_ce0;
output  [63:0] inxn2_d0;
input  [63:0] inxn2_q0;
output   inxn2_we0;
output  [10:0] outxk1_address0;
output   outxk1_ce0;
output  [63:0] outxk1_d0;
input  [63:0] outxk1_q0;
output   outxk1_we0;
output  [63:0] out_r_din;
input   out_r_full_n;
output   out_r_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

wire    dummy_proc_fe_U0_ap_start;
wire    dummy_proc_fe_U0_ap_done;
wire    dummy_proc_fe_U0_ap_continue;
wire    dummy_proc_fe_U0_ap_idle;
wire    dummy_proc_fe_U0_ap_ready;
wire   [15:0] dummy_proc_fe_U0_config_fwd_data_V_din;
wire    dummy_proc_fe_U0_config_fwd_data_V_write;
wire   [15:0] dummy_proc_fe_U0_config_inv_data_V_din;
wire    dummy_proc_fe_U0_config_inv_data_V_write;
wire    dummy_proc_fe_U0_in_r_read;
wire   [10:0] dummy_proc_fe_U0_input_xn2_address0;
wire    dummy_proc_fe_U0_input_xn2_ce0;
wire   [63:0] dummy_proc_fe_U0_output_xn1_din;
wire    dummy_proc_fe_U0_output_xn1_write;
wire   [63:0] dummy_proc_fe_U0_output_xn2_din;
wire    dummy_proc_fe_U0_output_xn2_write;
reg    fft_config1_U0_ap_start;
wire    fft_config1_U0_ap_done;
wire    fft_config1_U0_ap_idle;
wire    fft_config1_U0_ap_ready;
wire    fft_config1_U0_xn_read;
wire   [63:0] fft_config1_U0_xk_din;
wire    fft_config1_U0_xk_write;
wire   [7:0] fft_config1_U0_status_data_V_din;
wire    fft_config1_U0_status_data_V_write;
wire    fft_config1_U0_config_ch_data_V_read;
reg    fft_config2_U0_ap_start;
wire    fft_config2_U0_ap_done;
wire    fft_config2_U0_ap_idle;
wire    fft_config2_U0_ap_ready;
wire    fft_config2_U0_xn_read;
wire   [63:0] fft_config2_U0_xk_din;
wire    fft_config2_U0_xk_write;
wire   [7:0] fft_config2_U0_status_data_V_din;
wire    fft_config2_U0_status_data_V_write;
wire    fft_config2_U0_config_ch_data_V_read;
wire    dummy_proc_be_U0_ap_start;
wire    dummy_proc_be_U0_ap_done;
wire    dummy_proc_be_U0_ap_continue;
wire    dummy_proc_be_U0_ap_idle;
wire    dummy_proc_be_U0_ap_ready;
wire   [10:0] dummy_proc_be_U0_coefs_address0;
wire    dummy_proc_be_U0_coefs_ce0;
wire    dummy_proc_be_U0_input_xk1_read;
wire    dummy_proc_be_U0_input_xk2_read;
wire   [10:0] dummy_proc_be_U0_output_xk1_address0;
wire    dummy_proc_be_U0_output_xk1_ce0;
wire    dummy_proc_be_U0_output_xk1_we0;
wire   [63:0] dummy_proc_be_U0_output_xk1_d0;
wire   [63:0] dummy_proc_be_U0_out_r_din;
wire    dummy_proc_be_U0_out_r_write;
wire    ap_sync_continue;
wire    fft_config_fwd_data_s_full_n;
wire   [15:0] fft_config_fwd_data_s_dout;
wire    fft_config_fwd_data_s_empty_n;
wire    fft_config_inv_data_s_full_n;
wire   [15:0] fft_config_inv_data_s_dout;
wire    fft_config_inv_data_s_empty_n;
wire    xn_channel_full_n;
wire   [63:0] xn_channel_dout;
wire    xn_channel_empty_n;
wire    xn2_channel_full_n;
wire   [63:0] xn2_channel_dout;
wire    xn2_channel_empty_n;
wire    xk_channel_full_n;
wire   [63:0] xk_channel_dout;
wire    xk_channel_empty_n;
wire    xk2_channel_full_n;
wire   [63:0] xk2_channel_dout;
wire    xk2_channel_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_dummy_proc_be_U0_ap_ready;
wire    ap_sync_dummy_proc_be_U0_ap_ready;
reg   [1:0] dummy_proc_be_U0_ap_ready_count;
reg    ap_sync_reg_dummy_proc_fe_U0_ap_ready;
wire    ap_sync_dummy_proc_fe_U0_ap_ready;
reg   [1:0] dummy_proc_fe_U0_ap_ready_count;

// power-on initialization
initial begin
#0 fft_config1_U0_ap_start = 1'b0;
#0 fft_config2_U0_ap_start = 1'b0;
#0 ap_sync_reg_dummy_proc_be_U0_ap_ready = 1'b0;
#0 dummy_proc_be_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_dummy_proc_fe_U0_ap_ready = 1'b0;
#0 dummy_proc_fe_U0_ap_ready_count = 2'd0;
end

dummy_proc_fe dummy_proc_fe_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dummy_proc_fe_U0_ap_start),
    .ap_done(dummy_proc_fe_U0_ap_done),
    .ap_continue(dummy_proc_fe_U0_ap_continue),
    .ap_idle(dummy_proc_fe_U0_ap_idle),
    .ap_ready(dummy_proc_fe_U0_ap_ready),
    .config_fwd_data_V_din(dummy_proc_fe_U0_config_fwd_data_V_din),
    .config_fwd_data_V_full_n(fft_config_fwd_data_s_full_n),
    .config_fwd_data_V_write(dummy_proc_fe_U0_config_fwd_data_V_write),
    .config_inv_data_V_din(dummy_proc_fe_U0_config_inv_data_V_din),
    .config_inv_data_V_full_n(fft_config_inv_data_s_full_n),
    .config_inv_data_V_write(dummy_proc_fe_U0_config_inv_data_V_write),
    .in_r_dout(in_r_dout),
    .in_r_empty_n(in_r_empty_n),
    .in_r_read(dummy_proc_fe_U0_in_r_read),
    .input_xn2_address0(dummy_proc_fe_U0_input_xn2_address0),
    .input_xn2_ce0(dummy_proc_fe_U0_input_xn2_ce0),
    .input_xn2_q0(inxn2_q0),
    .output_xn1_din(dummy_proc_fe_U0_output_xn1_din),
    .output_xn1_full_n(xn_channel_full_n),
    .output_xn1_write(dummy_proc_fe_U0_output_xn1_write),
    .output_xn2_din(dummy_proc_fe_U0_output_xn2_din),
    .output_xn2_full_n(xn2_channel_full_n),
    .output_xn2_write(dummy_proc_fe_U0_output_xn2_write)
);

fft_config1_s fft_config1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_config1_U0_ap_start),
    .ap_ce(1'b1),
    .ap_done(fft_config1_U0_ap_done),
    .ap_idle(fft_config1_U0_ap_idle),
    .ap_ready(fft_config1_U0_ap_ready),
    .xn_dout(xn_channel_dout),
    .xn_empty_n(xn_channel_empty_n),
    .xn_read(fft_config1_U0_xn_read),
    .xk_din(fft_config1_U0_xk_din),
    .xk_full_n(xk_channel_full_n),
    .xk_write(fft_config1_U0_xk_write),
    .status_data_V_din(fft_config1_U0_status_data_V_din),
    .status_data_V_full_n(1'b1),
    .status_data_V_write(fft_config1_U0_status_data_V_write),
    .config_ch_data_V_dout(fft_config_fwd_data_s_dout),
    .config_ch_data_V_empty_n(fft_config_fwd_data_s_empty_n),
    .config_ch_data_V_read(fft_config1_U0_config_ch_data_V_read)
);

fft_config2_s fft_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_config2_U0_ap_start),
    .ap_ce(1'b1),
    .ap_done(fft_config2_U0_ap_done),
    .ap_idle(fft_config2_U0_ap_idle),
    .ap_ready(fft_config2_U0_ap_ready),
    .xn_dout(xn2_channel_dout),
    .xn_empty_n(xn2_channel_empty_n),
    .xn_read(fft_config2_U0_xn_read),
    .xk_din(fft_config2_U0_xk_din),
    .xk_full_n(xk2_channel_full_n),
    .xk_write(fft_config2_U0_xk_write),
    .status_data_V_din(fft_config2_U0_status_data_V_din),
    .status_data_V_full_n(1'b1),
    .status_data_V_write(fft_config2_U0_status_data_V_write),
    .config_ch_data_V_dout(fft_config_inv_data_s_dout),
    .config_ch_data_V_empty_n(fft_config_inv_data_s_empty_n),
    .config_ch_data_V_read(fft_config2_U0_config_ch_data_V_read)
);

dummy_proc_be dummy_proc_be_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dummy_proc_be_U0_ap_start),
    .ap_done(dummy_proc_be_U0_ap_done),
    .ap_continue(dummy_proc_be_U0_ap_continue),
    .ap_idle(dummy_proc_be_U0_ap_idle),
    .ap_ready(dummy_proc_be_U0_ap_ready),
    .coefs_address0(dummy_proc_be_U0_coefs_address0),
    .coefs_ce0(dummy_proc_be_U0_coefs_ce0),
    .coefs_q0(coefs_q0),
    .input_xk1_dout(xk_channel_dout),
    .input_xk1_empty_n(xk_channel_empty_n),
    .input_xk1_read(dummy_proc_be_U0_input_xk1_read),
    .input_xk2_dout(xk2_channel_dout),
    .input_xk2_empty_n(xk2_channel_empty_n),
    .input_xk2_read(dummy_proc_be_U0_input_xk2_read),
    .output_xk1_address0(dummy_proc_be_U0_output_xk1_address0),
    .output_xk1_ce0(dummy_proc_be_U0_output_xk1_ce0),
    .output_xk1_we0(dummy_proc_be_U0_output_xk1_we0),
    .output_xk1_d0(dummy_proc_be_U0_output_xk1_d0),
    .out_r_din(dummy_proc_be_U0_out_r_din),
    .out_r_full_n(out_r_full_n),
    .out_r_write(dummy_proc_be_U0_out_r_write)
);

fifo_w16_d2048_A fft_config_fwd_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe_U0_config_fwd_data_V_din),
    .if_full_n(fft_config_fwd_data_s_full_n),
    .if_write(dummy_proc_fe_U0_config_fwd_data_V_write),
    .if_dout(fft_config_fwd_data_s_dout),
    .if_empty_n(fft_config_fwd_data_s_empty_n),
    .if_read(fft_config1_U0_config_ch_data_V_read)
);

fifo_w16_d2048_A fft_config_inv_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe_U0_config_inv_data_V_din),
    .if_full_n(fft_config_inv_data_s_full_n),
    .if_write(dummy_proc_fe_U0_config_inv_data_V_write),
    .if_dout(fft_config_inv_data_s_dout),
    .if_empty_n(fft_config_inv_data_s_empty_n),
    .if_read(fft_config2_U0_config_ch_data_V_read)
);

fifo_w64_d1344_A xn_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe_U0_output_xn1_din),
    .if_full_n(xn_channel_full_n),
    .if_write(dummy_proc_fe_U0_output_xn1_write),
    .if_dout(xn_channel_dout),
    .if_empty_n(xn_channel_empty_n),
    .if_read(fft_config1_U0_xn_read)
);

fifo_w64_d64_A xn2_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe_U0_output_xn2_din),
    .if_full_n(xn2_channel_full_n),
    .if_write(dummy_proc_fe_U0_output_xn2_write),
    .if_dout(xn2_channel_dout),
    .if_empty_n(xn2_channel_empty_n),
    .if_read(fft_config2_U0_xn_read)
);

fifo_w64_d64_A xk_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_xk_din),
    .if_full_n(xk_channel_full_n),
    .if_write(fft_config1_U0_xk_write),
    .if_dout(xk_channel_dout),
    .if_empty_n(xk_channel_empty_n),
    .if_read(dummy_proc_be_U0_input_xk1_read)
);

fifo_w64_d64_A xk2_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config2_U0_xk_din),
    .if_full_n(xk2_channel_full_n),
    .if_write(fft_config2_U0_xk_write),
    .if_dout(xk2_channel_dout),
    .if_empty_n(xk2_channel_empty_n),
    .if_read(dummy_proc_be_U0_input_xk2_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dummy_proc_be_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dummy_proc_be_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dummy_proc_be_U0_ap_ready <= ap_sync_dummy_proc_be_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dummy_proc_fe_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dummy_proc_fe_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dummy_proc_fe_U0_ap_ready <= ap_sync_dummy_proc_fe_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fft_config1_U0_ap_start <= 1'b0;
    end else begin
        fft_config1_U0_ap_start <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fft_config2_U0_ap_start <= 1'b0;
    end else begin
        fft_config2_U0_ap_start <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (dummy_proc_be_U0_ap_ready == 1'b0))) begin
        dummy_proc_be_U0_ap_ready_count <= (dummy_proc_be_U0_ap_ready_count - 2'd1);
    end else if (((dummy_proc_be_U0_ap_ready == 1'b1) & (ap_sync_ready == 1'b0))) begin
        dummy_proc_be_U0_ap_ready_count <= (dummy_proc_be_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (dummy_proc_fe_U0_ap_ready == 1'b0))) begin
        dummy_proc_fe_U0_ap_ready_count <= (dummy_proc_fe_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (dummy_proc_fe_U0_ap_ready == 1'b1))) begin
        dummy_proc_fe_U0_ap_ready_count <= (dummy_proc_fe_U0_ap_ready_count + 2'd1);
    end
end

assign ap_done = dummy_proc_be_U0_ap_done;

assign ap_idle = (fft_config2_U0_ap_idle & fft_config1_U0_ap_idle & dummy_proc_fe_U0_ap_idle & dummy_proc_be_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = dummy_proc_be_U0_ap_done;

assign ap_sync_dummy_proc_be_U0_ap_ready = (dummy_proc_be_U0_ap_ready | ap_sync_reg_dummy_proc_be_U0_ap_ready);

assign ap_sync_dummy_proc_fe_U0_ap_ready = (dummy_proc_fe_U0_ap_ready | ap_sync_reg_dummy_proc_fe_U0_ap_ready);

assign ap_sync_ready = (ap_sync_dummy_proc_fe_U0_ap_ready & ap_sync_dummy_proc_be_U0_ap_ready);

assign coefs_address0 = dummy_proc_be_U0_coefs_address0;

assign coefs_ce0 = dummy_proc_be_U0_coefs_ce0;

assign coefs_d0 = 64'd0;

assign coefs_we0 = 1'b0;

assign dummy_proc_be_U0_ap_continue = 1'b1;

assign dummy_proc_be_U0_ap_start = ((ap_sync_reg_dummy_proc_be_U0_ap_ready ^ 1'b1) & ap_start);

assign dummy_proc_fe_U0_ap_continue = 1'b1;

assign dummy_proc_fe_U0_ap_start = ((ap_sync_reg_dummy_proc_fe_U0_ap_ready ^ 1'b1) & ap_start);

assign in_r_read = dummy_proc_fe_U0_in_r_read;

assign inxn2_address0 = dummy_proc_fe_U0_input_xn2_address0;

assign inxn2_ce0 = dummy_proc_fe_U0_input_xn2_ce0;

assign inxn2_d0 = 64'd0;

assign inxn2_we0 = 1'b0;

assign out_r_din = dummy_proc_be_U0_out_r_din;

assign out_r_write = dummy_proc_be_U0_out_r_write;

assign outxk1_address0 = dummy_proc_be_U0_output_xk1_address0;

assign outxk1_ce0 = dummy_proc_be_U0_output_xk1_ce0;

assign outxk1_d0 = dummy_proc_be_U0_output_xk1_d0;

assign outxk1_we0 = dummy_proc_be_U0_output_xk1_we0;

endmodule //filter_top
